### ISSUE TITLE
Exportación estática

### ISSUE THREAD

**Issue by tnfAngel** [JSPaste/JSP-Frontend#107]
Creo que es lo mejor, ya que realmente no necesitamos el SSR bajo demanda, y con las pruebas que hice, la mejor forma de desactivarlo es esta.

**Comment by tnfAngel** [comment]
@JSPaste/developers que opinais de esto?

**Comment by inetol** [comment]
Que implicaciones traera esto cuando se añada el soporte para el backend?

**Comment by tnfAngel** [comment]
En mi caso tenia pensado fetchear los documentos en el cliente para poder soportar los custom URL asi que no tendria ninguna implicacion negativa

**Comment by tnfAngel** [comment]
Con custom URL me refiero a esto, esto permitirá por ejemplo usar https://paste.inetol.net/api/v2/documents/ en la instancia oficial. (y viceversa)
![image](https://github.com/JSPaste/Frontend/assets/57068341/d106a1b0-7517-4702-9ee5-18eedd0bf41b)
Hacerlo en el servidor podría tener problemas de seguridad, ratelimit y exposición de la dirección IP del servidor al hacer la request. Tampoco soportaría localhost (por no decir que cualquier ip/hostname privado lo mandaría a la red privada del servidor y eso sería un riesgo muy importante de seguridad).

**Comment by inetol** [comment]
Uy de que me suena esto que casi me cepillan la cabeza por abusar de un bug, podrias poner cualquier URL y petarlo a requests y a menos que en el servidor tenga un ratelimit o un filtro montando se va a pasar enviando requests el frontend y ya el resto te lo imaginas.

Se puede hacer lo mas client-side posible? Que obtenga el documento del backend el cliente?

**Comment by tnfAngel** [comment]
> Creo que se puede hacer en client-side que obtenga el documento y que lo enseñe en en frontend?

sip esa era la intencion, por lo que la exportación estatica funcionaría perfectamente

**Comment by tnfAngel** [comment]
simplemente habría un pequeño loader (igual ya hay cuando carga monaco, asi que mientras carga monaco tambien se podria cargar el document del back)
