### ISSUE TITLE
Optimización

### ISSUE THREAD

**Issue by inetol** [JSPaste/JSP-Frontend#11]
El frontend (para producción) ahora mismo genera una carga demasiado alta para el procesador cuando un usuario accede al sitio, Next.js no parece estar optimizando correctamente, generando caché o renderizando el sitio de forma óptima.

Se tendrá que leer ["el librito"](https://nextjs.org/docs/app/building-your-application/optimizing) para mitigar este problema cuanto antes mejor.

**Comment by tnfAngel** [comment]
Quizás sea por el editor Monaco, ya que es bastante completo y necesita cargar varias cosas, por lo que veo no hay re-renders innecesarios, ni siquiera cuando se escribe en el editor (ya que no usa React), lo único que noto es que hay bastante peso en la carga inicial de JS
![imagen](https://github.com/JSPaste/JSP-Frontend/assets/57068341/a6c4e4b8-b52f-44b5-a281-8a83e1664549)

**Comment by tnfAngel** [comment]
Monaco es bastante grande
![imagen](https://github.com/JSPaste/JSP-Frontend/assets/57068341/ce32e867-6b6f-49ab-ad06-4d53bead2665)

**Comment by tnfAngel** [comment]
En cuanto a carga de CPU, si es verdad que hay varios scripts demasiado lentos, voy a ver qué se puede hacer
![imagen](https://github.com/JSPaste/JSP-Frontend/assets/57068341/9d41c6af-11ac-4b17-95b2-050242a6a3e3)

**Comment by inetol** [comment]
~Monaco en sí se carga todo de golpe, he añadido un parche para que cargue algunas partes del documento en paralelo y el tiempo de carga inicial se ha reducido un poco~

Haciendo que el servidor renderice el Editor (desconozco el impacto en el rendimiento con múltiples conexiones) he conseguido bajar el peso de la página al abrirla, sería beneficioso en móviles y cosas que no tengan demasiada potencia (?)

![Screenshot](https://github.com/JSPaste/JSP-Frontend/assets/34861290/e2a4a741-6faa-4c18-8e16-c786bb926916)

**Comment by tnfAngel** [comment]
Debería, además todo está fuertemente cacheado por CF, así que el servidor no debería recibir mucha carga

**Comment by inetol** [comment]
El commit [896d325](https://github.com/JSPaste/JSP-Frontend/commit/896d3255ffd6a9bf7c2f8c458921bc2b5b0c02c8) incluye algunas mejoras de optimización para remediar más o menos este problema

**Comment by tnfAngel** [comment]
He activado optimizaciones en el lado de CF, debería ser mejor ahora
Por cierto, la sección de controles a veces no aparece cuando se activa la carga dinámica, voy a revertir el cambio para ese componente
![imagen](https://github.com/JSPaste/JSP-Frontend/assets/57068341/950b85aa-05b3-4467-af55-15ced7498fab)

**Comment by tnfAngel** [comment]
![imagen](https://github.com/JSPaste/JSP-Frontend/assets/57068341/d8eecfeb-492c-41f3-8a8f-c966f7c351da)
sin embargo los tiempos siguen siendo bastante malos

**Comment by inetol** [comment]
> He activado optimizaciones en el lado de CF, debería ser mejor ahora Por cierto, la sección de controles a veces no aparece cuando se activa la carga dinámica, voy a revertir el cambio para ese componente ![imagen](https://private-user-images.githubusercontent.com/57068341/294715705-950b85aa-05b3-4467-af55-15ced7498fab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NzI1NzUsIm5iZiI6MTcwNDU3MjI3NSwicGF0aCI6Ii81NzA2ODM0MS8yOTQ3MTU3MDUtOTUwYjg1YWEtMDViMy00NDY3LWFmNTUtMTVjZWQ3NDk4ZmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDIwMTc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViMDk1MmExMDNjZjIwNmYwNTY4NzBiNTJhMDM3ZjZlMThkMjRiODliMTI3MzM4NjUyMmYzNjllMjg4ZDAzOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ggnyi47vTgc1MuOAlIPSZW3BUXBpcVrX7eP_Zh1-loo)

Ya deberia estar arreglado

**Comment by inetol** [comment]
> ![imagen](https://private-user-images.githubusercontent.com/57068341/294715754-d8eecfeb-492c-41f3-8a8f-c966f7c351da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NzI1NzUsIm5iZiI6MTcwNDU3MjI3NSwicGF0aCI6Ii81NzA2ODM0MS8yOTQ3MTU3NTQtZDhlZWNmZWItNDkyYy00MWYzLThhOGYtYzk2NmY3YzM1MWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDIwMTc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhYmU4NjBlZDQ1ZGI1NzVjODQ4MjJmZDhkODJkMDEzMDNhZmRmMmE5MmI5YzhlYWRjMGFmYTA5YWMzMmY5M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WhTQVFh4Q4_zHF0gN7e2qoQyv7-1jguqUwH1LSyb0n4) sin embargo los tiempos siguen siendo bastante malos

Si tio, no sé qué más hacerle para reducir la carga al cliente. Ya se me ocurrirá algo

**Comment by tnfAngel** [comment]
Dw, se puede aparcar porque el problema no es tan grande y solo afectará notablemente a los dispositivos de bajo rendimiento

**Comment by inetol** [comment]
> Dw, se puede aparcar porque el problema no es tan grande y solo afectará notablemente a los dispositivos de bajo rendimiento

El Rocket Loader de CF da más problemas que otra cosa, apuesto a que por el simple hecho de existir la carga de scripts va más lenta

**Comment by tnfAngel** [comment]
Lo voy a quitar

**Comment by jc-discdev** [comment]
Podriamos probar con lo de cloudflare que analiza que es lo que hace que cargue lento

**Comment by inetol** [comment]
Con el último commit de la rama dev veo que el problema que tiene el sitio es que tiene saturado el hilo principal porque más de un 90% es puro JS que se ejecuta a la vez. Se podría usar preload con algunos recursos o retrasar la carga por ejemplo del componente de ajustes hasta que abrieses el menú, como casi todo lo maneja NextJS no sé todavía como hacerlo adecuadamente.

![Screenshot](https://github.com/JSPaste/JSP-Frontend/assets/34861290/d0678f13-1de6-474b-9c38-71e634387ae5)

**Comment by inetol** [comment]
Probando de quitar la carga dinámica se recorta casi a la mitad la cantidad de peticiones que se hace al servidor y eso se puso por si le colaba al cliente de cargar recursos cuando lo necesitase, así que de momento se va a fuera

![Screenshot](https://github.com/JSPaste/JSP-Frontend/assets/34861290/0964355f-191a-4d1f-9743-93d34461ba48)

**Comment by jc-discdev** [comment]
El rocket loader de cloudflare o algun servicio de caching de la misma no ayudaría?

**Comment by tnfAngel** [comment]
Genial, yo activé esta opción https://nextjs.org/docs/app/building-your-application/optimizing/scripts#offloading-scripts-to-a-web-worker-experimental

**Comment by tnfAngel** [comment]
Ah, pero no funciona en app directory aún

**Comment by inetol** [comment]
> El rocket loader de cloudflare o algun servicio de caching de la misma no ayudaría?

Prácticamente nada, además es propenso a romper la página

**Comment by inetol** [comment]
> Genial, yo activé esta opción https://nextjs.org/docs/app/building-your-application/optimizing/scripts#offloading-scripts-to-a-web-worker-experimental

Eso ya ayudaría mas a repartir la carga por varios hilos

**Comment by inetol** [comment]
@tnfAngel Sería posible mover todos los Modals para que carguen dinámicamente? Ahora mismo todo eso se incluye en la carga inicial de la página y se podría evitar bastante overhead.

Intente hacerlo en #57 pero como no funcionaba correctamente lo deshice

**Comment by tnfAngel** [comment]
> @tnfAngel Sería posible mover todos los Modals para que carguen dinámicamente? Ahora mismo todo eso se incluye en la carga inicial de la página y se podría evitar bastante overhead.
> 
> Intente hacerlo en #57 pero como no funcionaba correctamente lo deshice

Vale, voy a mirar

**Comment by tnfAngel** [comment]
según lo que leo, los modals son "lazy" por defecto https://github.com/chakra-ui/chakra-ui/discussions/5569, y no se renderizan ni se agregan al HTML hasta que los abres, lo unico que sería adecuado es "separarlos" del chunk principal

**Comment by inetol** [comment]
> según lo que leo, los modals son "lazy" por defecto [chakra-ui/chakra-ui#5569](https://github.com/chakra-ui/chakra-ui/discussions/5569), y no se renderizan ni se agregan al HTML hasta que los abres, lo unico que sería adecuado es "separarlos" del chunk principal

Mierda es verdad, y separarlos en otro chunk no debería de arreglarlo, como mucho se podrían liberar 10kB, si lo comparas con Monaco son bastante insignificantes

![Screenshot](https://github.com/JSPaste/JSP-Frontend/assets/34861290/98aa3f3b-6e23-4376-bf71-80c275baad5e)

**Comment by tnfAngel** [comment]
> > según lo que leo, los modals son "lazy" por defecto [chakra-ui/chakra-ui#5569](https://github.com/chakra-ui/chakra-ui/discussions/5569), y no se renderizan ni se agregan al HTML hasta que los abres, lo unico que sería adecuado es "separarlos" del chunk principal
> 
> Mierda es verdad, y separarlos en otro chunk no debería de arreglarlo, como mucho se podrían liberar 10kB, si lo comparas con Monaco son bastante insignificantes
> 
> ![Screenshot](https://github.com/JSPaste/JSP-Frontend/assets/34861290/98aa3f3b-6e23-4376-bf71-80c275baad5e)
> 

ya, tienes razón

**Comment by inetol** [comment]
Antes (5990ee0d0d178dbe80d781bf99b3563743d262da):
![Screenshot](https://github.com/user-attachments/assets/0c1932b3-0f95-43c5-b961-22ab469297d1)

Ahora (f09bf0db3bd26cc8d8eaee75f0887fe57bbcac57):
![Screenshot](https://github.com/user-attachments/assets/6ebd3b87-0b31-46f8-90f3-c572d84466f0)

El chunk que tiene más uso del thread es el propio React, el otro pequeño es Codemirror. Yo ya lo considero aceptable, pero si se quisiera optimizar más se podría reemplazar React con Preact o usar Solid directamente.

También hay otras mejoras en el propio framework que no están aplicadas actualmente y podrían traer una mejora sustancial:
* https://vike.dev/ssr (problemas con los temas. No se ha probado su desempeño)
* https://vike.dev/prerender (#123, la arquitectura es distinta y abre la posibilidad de hacerlo híbrido. No se ha probado su desempeño)
* https://vike.dev/preloading#early-hints (pendiente)
