### ISSUE TITLE
Lefthook problematico

### ISSUE THREAD

**Issue by tnfAngel** [JSPaste/JSP-Frontend#110]
Se detecta como virus: https://github.com/evilmartians/lefthook/issues/722

Esto hace imposible usarlo cuando tienes un antivirus

(mismo problema en el backend)

**Comment by inetol** [comment]
No parece haber nada a primera vista, pero he hecho downgrade a la 1.6.8 para ambos repos en las ramas `dev`

**Comment by inetol** [comment]
Ya tendría que estar solucionado con la 1.6.14
