### ISSUE TITLE
Editor CodeMirror

### ISSUE THREAD

**Issue by inetol** [JSPaste/JSP-Frontend#111]
Hace unos meses buscando soluciones al PR #11 encontré CodeMirror como mejor alternativa a Monaco (en teoría), pero como ya implementaba sus propios eventos DOM pase un poco del tema (motivo también de porque abrí el PR #87).

Hoy he visto que sí que hay ya un componente de React de CodeMirror bien mantenido por lo que sería una buena idea probar el desempeño de ese editor bajo Next.js.

https://uiwjs.github.io/react-codemirror/

cc/ @tnfAngel

**Comment by tnfAngel** [comment]
tiene buena pinta, luego lo miro con profundidad
