### ISSUE TITLE
Soporte para múltiples editores

### ISSUE THREAD

**Issue by tnfAngel** [JSPaste/JSP-Frontend#113]
Estaría bien poner una opción para poder soportar multiples editores, por ejemplo que el default sea CodeMirror pero también puedas seleccionar Monaco si lo prefieres (y para no desaprovechar lo que ya funciona en Monaco)

**Comment by inetol** [comment]
No sé hasta que punto se pueden mantener bien dos editores compartiendo temas y funcionalidades 🤔

**Comment by tnfAngel** [comment]
Primero termino el CodeMirror y luego veo, pero cada editor puede tener sus temas independientes y quizas separalos de la UI, o simplemente tener temas comunes, en el tema de las funcionalidades se puede hacer un adaptador

**Comment by inetol** [comment]
@tnfAngel Reevalúa este issue si quieres mantenerlo vigente. Es *posible* añadir Monaco a la par con Codemirror, pero añade un extra de mantenimiento que no me puedo permitir ahora mismo, hasta donde se Monaco tampoco añade mucho más de lo que ya tiene Codemirror (el minimapa y los shortcuts, quitando el soporte oficial para movil)

**Comment by tnfAngel** [comment]
No es viable de momento
