### ISSUE TITLE
Problema de refs en react 19 con chakra-ui

### ISSUE THREAD

**Issue by tnfAngel** [JSPaste/JSP-Frontend#115]
De momento existe este problema con el SettingsPopover y los SelectModal, esto es debido a los nuevos refs de react, los cuales ahora se pasan como prop (la verdad deberían haber hecho eso desde el inicio pero en fin) y han hecho que forwardRef ya no funcione, y chakra-ui usa los refs antiguos para estos componentes, asi que es cuestión de esperar a que lo arreglen
En el caso de SettingsPopover no se posiciona correctamente por el ref de popper.js
![image](https://github.com/JSPaste/Frontend/assets/57068341/23acfe69-7ea9-4d00-b19b-3e52b8b91914)
en el caso de los SelectModal, ni siquiera se montan

Related: https://github.com/chakra-ui/chakra-ui/issues/8519

**Comment by inetol** [comment]
Por el momento se puede mantener como estaba con los forwardRef (es solo un warning de deprecation que lo quitaran en alguna versión futura de React creo?)

**Comment by inetol** [comment]
Prueba a ver si 3.0.0-next.0 soluciona este issue que se está usando la versión estable de chakra-ui

**Comment by tnfAngel** [comment]
soy yo o hay un montón de breaking changes?
![image](https://github.com/JSPaste/Frontend/assets/57068341/a78917cf-e598-43fe-b660-6034fc418ad6)

**Comment by tnfAngel** [comment]
Y no son solo los tipos 
![image](https://github.com/JSPaste/Frontend/assets/57068341/d31779be-a9e6-4b99-a907-437bd52985c8)

**Comment by tnfAngel** [comment]
Entiendo que es una major pero la mitad de las cosas no están o no funcionan

supongo que habrá que esperar

**Comment by inetol** [comment]
Hay un puñado de cambios importantes: https://github.com/chakra-ui/chakra-ui/releases/tag/%40chakra-ui%2Freact%403.0.0-next.0

En principio tendría que estar todo allí

**Comment by tnfAngel** [comment]
Ah vale, pero es para la v3 de chakra-ui, que todavia no ha salido y se esta haciendo, no para react 19

**Comment by inetol** [comment]
~Pero quizas ya añada el soporte para React 19~ No lo añade

**Comment by inetol** [comment]
Este issue ya no es válido: f09bf0db3bd26cc8d8eaee75f0887fe57bbcac57
