### ISSUE TITLE
¿Exportación estática o server side?

### ISSUE THREAD

**Issue by inetol** [JSPaste/JSP-Frontend#123]
En el PR #108 se añadió el soporte para exportar todo a estático y que se procese el Frontend client-side. Creo que ya con esta frase se puede apreciar el problema que quiero comentar aquí, pero antes voy a poner unas comparaciones específicas...

A diferencia del modo server normal, en el modo export se exporta todo (o parte) el framework de Next.js y sus dependencias para que se ejecute en client-side. El cliente tendrá más carga de la habitual en procesar todo el Frontend, algo que ya se quería evitar en #11 

En el modo export, las redirecciones no se pueden hacer eficientemente a menos que se use un servidor web (como se está usando ahora con serve), el problema de esto es que deja poca flexibilidad si se quiere usar otros sistemas. Es posible hacer las redirecciones directamente sin necesidad de configurarlas en el servidor web, pero cada redirección que se tenga que hacer es muy costosa porque se tienen que cargar todos los chunks globales donde está el framework de Next.js antes de poder hacer la redirección.

No veo mucho margen de mejora el modo export por las limitaciones y guarradas que trae usarlo, dad vuestra opinión si mantenerlo aporta algo o de lo contrario revertir el cambio al modo servidor.

cc/ @JSPaste/developers

**Comment by tnfAngel** [comment]
Entiendo que es un modo limitado y puede afectar el rendimiento del cliente, por lo que no tengo problema en revertirlo, pero era mayoritariamente porque la mayoria de las features que ofrece Next no se estan aprovechando, además de que hay un problema y es que las paginas estáticas con rutas dinámicas tienen el SSR bajo demanda en cada request, aunque las paginas en si sean estáticas y el contenido que se ofrezca al cliente sea siempre el mismo; cosa que no me hace mucha gracia ya que es prácticamente un gasto de capacidad cómputo innecesario, pero bueno, entiendo que se quiera revertir y que es mas que nada un bug de next

**Comment by tnfAngel** [comment]
Luego pruebo una especie de workaround a ver si consigo arreglar eso

**Comment by inetol** [comment]
OK, igualmente estos días jugando con el PR #122 si no aparecen problemas y termino fusionando la rama en #112 es posible que reviva de seguido el PR #87 así que tampoco te comas mucho la cabeza si no consigues mitigar estos inconvenientes.
