### ISSUE TITLE
Overhead en standalone

### ISSUE THREAD

**Issue by inetol** [JSPaste/JSP-Frontend#137]
Me ha llamado la atención de las pruebas que hice en #112 que al recuperar los chunks tardase tanto. He hecho 4 pruebas locales, dos en esta rama `codemirror` y otras dos en la rama `stable` en sus últimos commits comparando los requests ejecutando el servidor con next y otro con el servidor standalone, definitivamente hay un overhead de ~30ms casi duplicando el tiempo para finalizar la carga de la página (ignorando peticiones externas y los favicon)...

`codemirror`: *(bun run build:standalone)*
* `bun next start`
![Screenshot](https://github.com/user-attachments/assets/15943e2d-1613-432f-8454-575e88d115ac)

* `bun run .next/standalone/server.js`
![Screenshot](https://github.com/user-attachments/assets/332dff5d-bdac-42f2-be3e-779771f68e9d)

`stable`: *(bun run build:standalone)*
* `bun next start`
![Screenshot](https://github.com/user-attachments/assets/68b36712-a3f9-4ed8-abaf-d473fc5cd1b6)

* `bun run .next/standalone/server.js`
![Screenshot](https://github.com/user-attachments/assets/ca9551fa-8ea9-4b48-9093-c99f638416a4)

Parece más un problema de diseño de Next porque internamente el standalone sigue utilizando el mismo servidor que utiliza next start, pero con las dependencias recortadas y cuatro tonterías más, desconozco el motivo exacto de que tarde tanto en recuperar los chunks.

La solución a corto plazo sería remplazar el standalone con el servidor normal añadiendo ~200MB adicionales cosa que no voy a hacer.

**Comment by tnfAngel** [comment]
tiene toda la pinta de bug de next

**Comment by inetol** [comment]
Con el último commit añadiendo el highlight y los temas en el editor se agrava muchísimo más, tanto que ni la gráfica cabe en los devtools, patético

![Screenshot](https://github.com/user-attachments/assets/f26c903e-2623-4985-b919-76bb525f71d5)

Esto no es lag del cliente, sino que el tiempo de respuesta y descarga desde el servidor es alto, en los ficheros grandes se entiende, pero solo son 500KB en localhost y de media tarda 80ms solo para transferirlo al cliente.

En el modo server normal apenas ha habido cambio.
