### ISSUE TITLE
Ratelimit demasiado agresivo

### ISSUE THREAD

**Issue by inetol** [JSPaste/JSP-Frontend#18]
El ratelimit que hay ahora mismo en el middleware (no hablo de CF) de [jspaste.eu](jspaste.eu) es absurdamente alto, si cuentas las solicitudes que haces para cargar el Monaco, el tema y todo lo que hay detrás, solo te falta refrescar la página 2 veces más y ya entraras al ratelimit.

![Screenshot](https://github.com/JSPaste/JSP-Frontend/assets/34861290/0175ce50-2c04-4eb2-8dba-e2e20509ae1d)

**Comment by tnfAngel** [comment]
Voy a reducirlo un poco, actualmente tengo que si hay 50 solicitudes en 10 segundos de Ratelimit de 10 segundos, lo subo a 80 request en 10 segundos

**Comment by tnfAngel** [comment]
Listo, lo he subido a 100

**Comment by inetol** [comment]
Con 100r/10s ya a menos que vayas refrescando constantemente la página *no debería* saltar de nuevo
