### ISSUE TITLE
Ocultar texto introductivo

### ISSUE THREAD

**Issue by inetol** [JSPaste/JSP-Frontend#21]
![Screenshot](https://github.com/JSPaste/JSP-Frontend/assets/34861290/2fc83db1-1029-47a5-97ef-423c27f2e585)

Se podría añadir ese texto de fondo si no hay nada en el Monaco? Así también se previene que alguien guarde sin parar con ese texto predeterminado.

_Originally posted by @inetol in https://github.com/JSPaste/JSP-Frontend/pull/17#pullrequestreview-1807587097_

**Comment by tnfAngel** [comment]
Sería bueno simplemente eliminar el texto cuando se haga la request al servidor con replace? o eliminarlo cuando se escriba en el textarea?

**Comment by inetol** [comment]
La primera opción si se implementa en client side entonces sí, pero veo más elegante la segunda

**Comment by tnfAngel** [comment]
Tenía pensado hacerlo en el client side, pero voy a probar la segunda a ver que tal queda

**Comment by jc-discdev** [comment]
Veo más factible la segunda, o si no simplemente bloquear que se guarde si esta ese texto.

**Comment by tnfAngel** [comment]
La segunda de prueba para ver como queda: 312a41b1b7ca00bdd9205bf1fea31024898cfb52

**Comment by tnfAngel** [comment]
(ya está en producción)

**Comment by inetol** [comment]
Te devuelve el cursor al final donde hay el último LF cuando escribes a la primera o segunda línea. Aquí el newline no hace falta ya si total el texto va a desaparecer. Mira el último commit y válida si funciona correctamente.

**Comment by tnfAngel** [comment]
> Te devuelve el cursor al final donde hay el último LF cuando escribes a la primera o segunda línea. Aquí el newline no hace falta ya si total el texto va a desaparecer. Mira el último commit y válida si funciona correctamente.

Funciona, pero el cursor lo manda al final del comentario, no sé que quedaría mejor, que se quede en la columna 1 o dejarlo así
![imagen](https://github.com/JSPaste/JSP-Frontend/assets/57068341/af482905-b549-4536-bf8e-c682c6c7e670)

**Comment by tnfAngel** [comment]
![imagen](https://github.com/JSPaste/JSP-Frontend/assets/57068341/bd976aa4-1534-420b-8a35-973890fba264)
Con cursor en columna 1

**Comment by tnfAngel** [comment]
Hmm, creo que mejor dejarlo al final del comentario, qué opináis?

**Comment by jc-discdev** [comment]
> Hmm, creo que mejor dejarlo al final del comentario, qué opináis?

Teniendo en cuenta que se va a boorar al principio opino que queda mejor porque al final queda aleatorio que vuelva hacia delante.

**Comment by inetol** [comment]
Si se pudiera ocultar yo creo que quedaria bastante bien (y luego hacerlo aparecer de nuevo), pero sino que el cursor vaya al final

**Comment by jc-discdev** [comment]
> Si se pudiera ocultar yo creo que quedaria bastante bien (y luego hacerlo aparecer de nuevo), pero sino que el cursor vaya al final

Y si se hace un aviso arriba cuando se abra la web? Que diga eso mismo y que haga dismiss cuando empieces a escribir?

**Comment by inetol** [comment]
> Y si se hace un aviso arriba cuando se abra la web? Que diga eso mismo y que haga dismiss cuando empieces a escribir?

No me convence tener ventanas, además que así se ve más limpio y sin distracciones

**Comment by jc-discdev** [comment]
> No me convence tener ventanas, además que así se ve más limpio y sin distracciones

Eso es cierto, pero oculto no liaría?

**Comment by tnfAngel** [comment]
Creo que ahora debería estar bien

**Comment by tnfAngel** [comment]
al menos a mi me convence

**Comment by jc-discdev** [comment]
A mi también

**Comment by inetol** [comment]
Yup, ya más adelante se repasará ese detalle
