### ISSUE TITLE
Mejoras interfaz móvil

### ISSUE THREAD

**Issue by inetol** [JSPaste/JSP-Frontend#43]
La interfaz para móvil aunque no se haya dado demasiada importancia no presenta fallos, pero propongo unos cambios...

- La ventana de ajustes podría ir pegada abajo de la pantalla una vez se cambie al estilo 2 columnas (el de 4 columnas tendría el mismo efecto obvio...)

- El visualizador de código a la derecha si Monaco permite deshabilitarlo cuando se reduzca al estilo de 2 columnas (o directamente quitarlo si estás en móvil) entonces habría más espacio para las pantallas más estrechas.

![Screenshot](https://github.com/JSPaste/JSP-Frontend/assets/34861290/dd460e7e-b99b-412f-8940-f2f69f0a2472)

**Comment by tnfAngel** [comment]
En ello

**Comment by tnfAngel** [comment]
![Captura de pantalla 2024-01-07 a las 18 40 41](https://github.com/JSPaste/JSP-Frontend/assets/57068341/8094b21a-d75e-41c8-bbe2-d9b3f1b92c6a)
He desactivado el minimap de código y he mejorado los márgenes, sin embargo colocarlo abajo no se puede hacer fácilmente, pero colocarlo arriba si

**Comment by tnfAngel** [comment]
![Captura de pantalla 2024-01-07 a las 18 43 09](https://github.com/JSPaste/JSP-Frontend/assets/57068341/8ce4a092-12bf-43c6-a659-b445bca81cc8)
Así se vería colocado arriba

**Comment by inetol** [comment]
Entonces mejor déjalo al medio, ya veo que añadiste margin al componente y tampoco queda mal

**Comment by tnfAngel** [comment]
Vale

**Comment by inetol** [comment]
Cierro ya que la integración para móvil ya está bastante completa por ahora
