### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by inetol** [JSPaste/JSP-Frontend#48]
Parece la cosa más innecesaria ahora mismo, pero poder instalar la app de JSPaste en el móvil u ordenador y poder usarlo con un clic es algo que siempre he querido implementar en algún sitio.

Voy a ir trabajando en ello en una rama aparte.

**Comment by tnfAngel** [comment]
yo tenía en mente crear un webview o incluso nativo en Android y publicarlo en la play store, pero también es buena idea lo del PWA

**Comment by inetol** [comment]
> yo tenía en mente crear un webview o incluso nativo en Android y publicarlo en la play store, pero también es buena idea lo del PWA

La ventaja que tiene el PWA es que crearlo es bastante fácil, casi ni tienes que mantenerlo de forma regular y no tienes que depender de otras opciones porque todos los navegadores permiten instalarlo una vez visitas la página

**Comment by Mrgaton** [comment]
es solo poner un json creo

**Comment by inetol** [comment]
> es solo poner un json y ya

Usando solo el manifiesto no es suficiente para una buena implementación.
