### ISSUE TITLE
Añadir un endpoint para obtener un documento con url mas corta?

### ISSUE THREAD

**Issue by Mrgaton** [JSPaste/JSP-Frontend#70]
Que api/v2/documents/8S5?password=buenas

y api/v2/d/8S5/r?password=jeje

y que si no se especifique la version de la api se use la ultima?

**Comment by inetol** [comment]
/documents ya debería usar la última versión de la API disponible.

Los alias no los encuentro necesarios, porque necesitas un alias (versión recortada) del backend?

**Comment by Mrgaton** [comment]
Mas que nada era una idea para poder tener una version acortada de las urls para en casos especificos.

Pero si no lo ves bien pues nada.

**Comment by inetol** [comment]
cc/ @tnfAngel

**Comment by tnfAngel** [comment]
> Mas que nada era una idea para poder tener una version acortada de las urls para en casos especificos.
> 
> Pero si no lo ves bien pues nada.

Esto solo tendría sentido en el frontend, y ademas en el frontend ni siquiera se usan rutas tipo /documents sino que es tal cual /:key asi que no tiene sentido no?

**Comment by Mrgaton** [comment]
https://jspaste.eu/sdae/r

yo si le veo sentido pero como vosotros veais

**Comment by Mrgaton** [comment]
De echo pastebin usa ese metodo, y me gusta mucho pero ya os lo dejo a vosotros

**Comment by inetol** [comment]
> De echo pastebin usa ese metodo, y me gusta mucho pero ya os lo dejo a vosotros

JSP *sigue el mismo camino*, el Frontend *se supone* que tiene que devolver el documento en la raíz del path (por ejemplo: https://jspaste.eu/webiwabo) que será la forma corta de los path del Backend donde alli se leen como "https://jspaste.eu/documents/webiwabo" para la última versión de la API o "https://jspaste.eu/api/v1/documents/webiwabo" para una versión específica.

**Comment by Mrgaton** [comment]
Pues si ya son igual que pastebin solo falta que /r sea igual que /raw

**Comment by tnfAngel** [comment]
completed 631c32f
