### ISSUE TITLE
Biome no ignora .next

### ISSUE THREAD

**Issue by tnfAngel** [JSPaste/JSP-Frontend#80]
Biome no está ignorando la carpeta .next, sin embargo se encuenta en el ignore (un poco raro, suena a bug, btw esto hace imposible hacer commit debido al lefthook)

![imagen](https://github.com/JSPaste/Frontend/assets/57068341/70a69523-ee84-4e02-9e85-31c88f7a5520)

**Comment by inetol** [comment]
Lo que veo que no está ignorando es cuando ejecuta el organizeImports y me parece extraño porque este debería estar ligado al ignore del format (y porque en mi caso funcionaba todo correctamente), aunque podría ser algún bug presente en el ejecutable de Windows

**Comment by tnfAngel** [comment]
> Lo que veo que no está ignorando es cuando ejecuta el organizeImports y me parece extraño porque este debería estar ligado al ignore del format (y porque en mi caso funcionaba todo correctamente), aunque podría ser algún bug presente en el ejecutable de Windows

de momento poniendo el ignore en files ha funcionado
