### ISSUE TITLE
No se puede hacer zoom out en el texto

### ISSUE THREAD

**Issue by Mrgaton** [JSPaste/JSP-Frontend#85]
Cuando se intenta hacer zoom out en la pagina web en el apartado del contenido del  archivo no funciona

**Comment by inetol** [comment]
Esto es más una limitación del Monaco porque modifica los shortcuts del navegador para hacer otras acciones como presionar F1 para que se te abra el listado de comandos como en VSCode, se podrían añadir botones para aumentar o disminuir el tamaño del editor y eso también solucionaría el issue #55 ya que ya no estaríamos ligados a esta limitación

**Comment by tnfAngel** [comment]
No puedo reproducirlo, funciona con CTRL + - tanto en Firefox@127.0b3 como en Chrome@124.0.6367.208
![image](https://github.com/JSPaste/Frontend/assets/57068341/64148a7c-55d7-4a48-89c6-fe69607442b8)

**Comment by tnfAngel** [comment]
incluso se puede cambiar el tamaño de la fuente con el command palette
![image](https://github.com/JSPaste/Frontend/assets/57068341/a83906ab-3991-4146-9f2f-fc6ad574f7da)

**Comment by inetol** [comment]
Ya, pero con CTRL y la rueda del ratón mientras está dentro de Monaco entonces desplaza el contenido, no sé si sea el comportamiento esperado

**Comment by inetol** [comment]
#112
