### ISSUE TITLE
Framework

### ISSUE THREAD

**Issue by inetol** [JSPaste/JSP-Frontend#86]
No quiero ser aguafiestas, pero Next.js *(ni React)* nunca ha sido mi framework por excelencia *(el desarrollo en frontend no lo es)*, pero creo que puede haber mejores alternativas actualmente como Astro para un sitio "simple" como el Frontend que le pueda beneficiar.

**Comment by tnfAngel** [comment]
No se nada de astro, que beneficios puede aportar frente a next.js?

**Comment by inetol** [comment]
> No se nada de astro, que beneficios puede aportar frente a next.js?

Lo estuve probando y genera mucho más código inmutable (HTML y CSS), además de tener una mejor compatibilidad con Bun y tener una sintaxis más concisa (en mi opinión). Por el momento voy probando a ver si no da demasiados problemas.
